  export const CAPSULES_DATA = 'CAPSULES_DATA'
  export const CAPSULES_DATA_SUCCESS = 'CAPSULES_DATA_SUCCESS'
  export const CAPSULES_DATA_FAILURE = 'CAPSULES_DATA_FAILURE'

  export const CAPSULES_SEARIAL_DATA = 'CAPSULES_SEARIAL_DATA'
  export const CAPSULES_SEARIAL_DATA_SUCCESS = 'CAPSULES_SEARIAL_DATA_SUCCESS'
  export const CAPSULES_SEARIAL_DATA_FAILURE = 'CAPSULES_SEARIAL_DATA_FAILURE'
