export const CORES_DATA = 'CORES_DATA'
export const CORES_DATA_SUCCESS = 'CORES_DATA_SUCCESS'
export const CORES_DATA_FAILURE = 'CORES_DATA_FAILURE'

export const CORES_SEARIAL_DATA = 'CORES_SEARIAL_DATA'
export const CORES_SEARIAL_DATA_SUCCESS = 'CORES_SEARIAL_DATA_SUCCESS'
export const CORES_SEARIAL_DATA_FAILURE = 'CORES_SEARIAL_DATA_FAILURE'
